### ISSUE TITLE
Sensors disappeared

### ISSUE THREAD

**Issue by phobiccarrot** [cyberjunky/home-assistant-google_fit#14]
Everything was working well, but yesterday, the sensors all disappeared from HA.  I have tried re-downloading the integration.  It had been fine for a while.

**Comment by PowZone** [comment]
Same issue here :/

How can we install a new sensor on versione 2022.2.0 ?

thank you!

**Comment by cyberjunky** [comment]
Stale issue, closing, please update to latest version and (re)open ticket if needed.
