### ISSUE TITLE
How to solve invalid response

### ISSUE THREAD

**Issue by Hadatko** [cyberjunky/home-assistant-google_fit#34]
Hi, i am getting this. Changing timezone not helped.
![image](https://user-images.githubusercontent.com/13130700/221836943-31f7798b-fcb5-4ad4-aa48-8e75f6d186a8.png)

**Comment by joewesch** [comment]
I just tried to install this custom component today and got the same error.

**Comment by WebfinityDesign** [comment]
Same problem here. Looks like this addon is not maintained anymore

**Comment by milandzuris** [comment]
i think integration stop working, from day to day integration for me stop working

**Comment by YorkshireIoT** [comment]
I created a new Google Fit integration to try and fix this issue by configuring the credentials through the UI and using Home Assistants built in credentials manager. If you want to try it out (and log any issues if you find them) you can find it here: https://github.com/YorkshireIoT/ha-google-fit

**Comment by Hadatko** [comment]
> I created a new Google Fit integration to try and fix this issue by configuring the credentials through the UI and using Home Assistants built in credentials manager. If you want to try it out (and log any issues if you find them) you can find it here: https://github.com/YorkshireIoT/ha-google-fit

That is great but i have still error 
![image](https://user-images.githubusercontent.com/13130700/229375684-25bdc362-acc2-4801-a394-4595c1830e9a.png)

**Comment by YorkshireIoT** [comment]
> > I created a new Google Fit integration to try and fix this issue by configuring the credentials through the UI and using Home Assistants built in credentials manager. If you want to try it out (and log any issues if you find them) you can find it here: https://github.com/YorkshireIoT/ha-google-fit
> 
> That is great but i have still error ![image](https://user-images.githubusercontent.com/13130700/229375684-25bdc362-acc2-4801-a394-4595c1830e9a.png)

Hi, that sounds a lot like a Google API applications credentials issue. Double check you follow the linked instructions in the README to the home assistant docs for Google Mail.
Make sure you're not using any existing credentials, the type is web app, you've set the redirect URL exactly as described (not the JavaScript one) and finally that your application is published.

**Comment by crstian19** [comment]
> > I created a new Google Fit integration to try and fix this issue by configuring the credentials through the UI and using Home Assistants built in credentials manager. If you want to try it out (and log any issues if you find them) you can find it here: https://github.com/YorkshireIoT/ha-google-fit
> 
> That is great but i have still error ![image](https://user-images.githubusercontent.com/13130700/229375684-25bdc362-acc2-4801-a394-4595c1830e9a.png)

You have to use this URI: https://my.home-assistant.io/redirect/oauth works for me

**Comment by Hadatko** [comment]
Hi @YorkshireIoT , finaly i had time to dive into this. Previously i had to make something wrong. Now it looks like i created correct creditionals. But after adding integration it will not appear into list of integrations and i was also not able to add integration into room. Adding integration finish with 
![image](https://github.com/cyberjunky/home-assistant-google_fit/assets/13130700/68fea1f1-3d28-4110-9772-fbf575a0e235)

**Comment by YorkshireIoT** [comment]
> Hi @YorkshireIoT , finaly i had time to dive into this. Previously i had to make something wrong. Now it looks like i created correct creditionals. But after adding integration it will not appear into list of integrations and i was also not able to add integration into room. Adding integration finish with ![image](https://user-images.githubusercontent.com/13130700/250343797-68fea1f1-3d28-4110-9772-fbf575a0e235.png)

Hi @Hadatko, thanks for trying out my integration.

Could you create a new issue on my integration with the required debug logging attached and we'll try and sort it out there? That way we're not clogging up a different repository with a solution that probably isn't relevant (although feel free to mention this issue when you create the new one to link the two on GitHub)

Thanks

**Comment by Hadatko** [comment]
I agree with you. Closing as my initial issue was solved.
