### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'google_fit'.

### ISSUE THREAD

**Issue by tigattack** [cyberjunky/home-assistant-google_fit#4]
Hi. Thanks for this integration, it's awesome.

Just a heads up, I'm seeing the following warning in the log:  
`2021-03-25 10:47:57 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'google_fit'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'google_fit'`

**Comment by cyberjunky** [comment]
@tigattack thanks, I have added it to version 1.0.4, can you test it?

**Comment by tigattack** [comment]
Looks good, thanks!
